import 'package:flutter/material.dart';

import 'user/achievements.dart';

List<Achievement> achievementsInfo = [
  Achievement(
    icon: Icons.school,
    name: "First Step",
    description: "Complete your first lesson",
    progress: 0,
    target: 1,
    type: AchievementType.courseCompletion,
    color: Colors.blue,
  ),
  Achievement(
    icon: Icons.emoji_events,
    name: "Perfect Score",
    description: "Get 100% on any test",
    progress: 0,
    target: 1,
    type: AchievementType.perfectScore,
    color: Colors.amber,
  ),
  Achievement(
    icon: Icons.local_fire_department,
    name: "3-Day Streak",
    description: "Learn for 3 consecutive days",
    progress: 0,
    target: 3,
    type: AchievementType.streak,
    color: Colors.red,
  ),
  Achievement(
    icon: Icons.timer,
    name: "Speed Learner",
    description: "Complete 5 lessons in one day",
    progress: 0,
    target: 5,
    type: AchievementType.speed,
    color: Colors.green,
  ),
  Achievement(
    icon: Icons.trending_up,
    name: "Consistent",
    description: "Complete 10 lessons total",
    progress: 0,
    target: 10,
    type: AchievementType.consistency,
    color: Colors.purple,
  ),
  Achievement(
    icon: Icons.explore,
    name: "Course Explorer",
    description: "Register for 3 different courses",
    progress: 0,
    target: 3,
    type: AchievementType.explorer,
    color: Colors.teal,
  ),
  Achievement(
    icon: Icons.star,
    name: "Master Student",
    description: "Complete all lessons in one course",
    progress: 0,
    target: 1,
    type: AchievementType.master,
    color: Colors.deepOrange,
  ),
  Achievement(
    icon: Icons.people,
    name: "Social Learner",
    description: "Share your progress 5 times",
    progress: 0,
    target: 5,
    type: AchievementType.social,
    color: Colors.indigo,
  ),
  Achievement(
    icon: Icons.lightbulb,
    name: "Quick Thinker",
    description: "Answer 20 questions correctly",
    progress: 0,
    target: 20,
    type: AchievementType.speed,
    color: Colors.cyan,
  ),
  Achievement(
    icon: Icons.rocket_launch,
    name: "Fast Starter",
    description: "Complete first lesson in under 5 minutes",
    progress: 0,
    target: 1,
    type: AchievementType.speed,
    color: Colors.pink,
  ),
  // Achievement(
  //   icon: Icons.done_all,
  //   name: "Completionist",
  //   description: "Finish all available courses",
  //   progress: 0,
  //   target: coursesInfo.length,
  //   type: AchievementType.courseCompletion,
  //   color: Colors.deepPurple,
  // ),
  Achievement(
    icon: Icons.celebration,
    name: "Perfect Week",
    description: "Learn every day for 7 days",
    progress: 0,
    target: 7,
    type: AchievementType.streak,
    color: Colors.orange,
  ),
];
