// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg1Lqz8wz4Z6jsWE6s-YyEah4c62oWHwQ',
    appId: '1:140855462814:web:9efcd1cdf6dd59d005e48f',
    messagingSenderId: '140855462814',
    projectId: 'sophiapath-project',
    authDomain: 'sophiapath-project.firebaseapp.com',
    storageBucket: 'sophiapath-project.firebasestorage.app',
    measurementId: 'G-HJS61LLRDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV4jUOuQrNIXiKfC5-cijFJKDHPNthhEw',
    appId: '1:140855462814:android:bf08dd001836bab605e48f',
    messagingSenderId: '140855462814',
    projectId: 'sophiapath-project',
    storageBucket: 'sophiapath-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXheBdeSoAXdyzhKyhQKKTsdWqvxcEb7A',
    appId: '1:140855462814:ios:081c473d4c7b79d205e48f',
    messagingSenderId: '140855462814',
    projectId: 'sophiapath-project',
    storageBucket: 'sophiapath-project.firebasestorage.app',
    iosBundleId: 'com.example.sophiaPath',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXheBdeSoAXdyzhKyhQKKTsdWqvxcEb7A',
    appId: '1:140855462814:ios:081c473d4c7b79d205e48f',
    messagingSenderId: '140855462814',
    projectId: 'sophiapath-project',
    storageBucket: 'sophiapath-project.firebasestorage.app',
    iosBundleId: 'com.example.sophiaPath',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg1Lqz8wz4Z6jsWE6s-YyEah4c62oWHwQ',
    appId: '1:140855462814:web:806ea5991b38e41c05e48f',
    messagingSenderId: '140855462814',
    projectId: 'sophiapath-project',
    authDomain: 'sophiapath-project.firebaseapp.com',
    storageBucket: 'sophiapath-project.firebasestorage.app',
    measurementId: 'G-YRM7RRSR5E',
  );
}
